version: '3'
services:
  jupyter_lab:
    build:
      context: .
      #イメージ元はdockerhubではなく，Dirのdockerfileそのものを参照する
      dockerfile: Dockerfile
    image: hunterAI
    ports:
    - "8080:8888"
    volumes:
    - .:/workdir